# Generated by Django 5.0.1 on 2024-01-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fridge_meattemperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meattemperature',
            name='fridge',
        ),
        migrations.RemoveField(
            model_name='meattemperature',
            name='user',
        ),
        migrations.DeleteModel(
            name='Fridge',
        ),
        migrations.DeleteModel(
            name='MeatTemperature',
        ),
    ]
